sudo: false
language: node_js
node_js: stable
before_script:
  - wget https://github.com/rust-lang-nursery/mdBook/releases/download/v0.3.0/mdbook-v0.3.0-x86_64-unknown-linux-gnu.tar.gz
  - tar -xvf mdbook-v0.3.0-x86_64-unknown-linux-gnu.tar.gz
  - export PATH=$TRAVIS_BUILD_DIR:$PATH
script:
  - npm run test
  - mdbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
