[book]
authors = ["yumetodo"]
multilingual = false
src = "src"
title = "転生した二人は魔術とITを融合させる"
description = "転生した二人は魔術とITを融合させる | 三次創作"
git-repository-url = "https://github.com/yumetodo/novel_two_people_who_transmigrated_make_magic_and_IT_fused"
